### ISSUE TITLE
Zipcode from outside of the US causes undefined error.

### ISSUE THREAD

**Issue by perogi** [perogi/zipcodes-perogi#11]
If you use a “valid” zipcode (5 digit string) but it’s not a valid zipcode, getting an undefined error

germanZipCode = "01465"
1) ZipCode Service Tests When getting zipcode with timezone information and zipcode is a valid length but not a US zip code "before each" hook for "then the res.statusCode is 500":
     TypeError: Cannot read property 'timeZoneId' of undefined
      at Object.lookupWithTime (node_modules/zipcodes-perogi/lib/index.js:16:33)
      at Object.invokeZipcodeTimezoneService (src/services/ZipCodeService.js:48:38)
      at Context.beforeEach (src/services/__test__/ZipCodeService.test.js:273:25)

**Comment by perogi** [comment]
Issue is in line 16 of index.js  - need to check for undefined info coming back from look up.

**Comment by perogi** [comment]
Committed.
